### ISSUE TITLE
redmine 5.x

### ISSUE THREAD

**Issue by whotopia** [nanego/redmine_magic_link#2]
to work with version 5. seems like this plugin might need change to init.rb:

```
#require 'redmine_magic_link/hooks'
require File.expand_path('lib/redmine_magic_link/hooks', __dir__)
```

There might be more.

**Comment by whotopia** [comment]
in plugins/redmine_datetime_custom_field/init.rb 

this should do it:

```
# Custom patches
#require_dependency 'redmine_datetime_custom_field/hooks'
require_dependency File.expand_path('lib/redmine_datetime_custom_field/hooks', __dir__)
```

There may be other 5.x compatibility issues, but this fixes the issue with the hooks.

**Comment by nanego** [comment]
Thank you for contributing.
The plugin has been updated and is now fully compatible with Redmine 5.
